### ISSUE TITLE
undefined symbol: mysql_real_escape_string_quote

### ISSUE THREAD

**Issue by ostrokach** [PyMySQL/mysqlclient-python#110]
I am getting an error:

```
ImportError: /opt/conda/envs/_test/lib/python3.5/site-packages/_mysql.cpython-35m-x86_64-linux-gnu.so: undefined symbol: mysql_real_escape_string_quote
```

When trying to build a conda package with mysqlclient master branch. I think this is caused by commit #109?

**Comment by methane** [comment]
Thanks for using bleeding edge code and reporting issue.

I assume you use MySQL >= 5.7.4 when building extension module, and MySQL < 5.7.4 when running.

Could you try this?

```
$ mysql_config

$ ldd /opt/conda/envs/_test/lib/python3.5/site-packages/_mysql.cpython-35m-x86_64-linux-gnu.so
```

**Comment by ostrokach** [comment]
Thank you for your quick response!

```
$ ldd /opt/conda/envs/_test/lib/python3.5/site-packages/_mysql.cpython-35m-x86_64-linux-gnu.so

linux-vdso.so.1 =>  (0x00007fffb23f6000)
libmysqlclient.so.18 => /opt/conda/envs/_test/lib/python3.5/site-packages/../../libmysqlclient.so.18 (0x00007f3f980d7000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3f97eb3000)
libm.so.6 => /lib64/libm.so.6 (0x00007f3f97c2f000)
librt.so.1 => /lib64/librt.so.1 (0x00007f3f97a27000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f3f97822000)
libpython3.5m.so.1.0 => /opt/conda/envs/_test/lib/python3.5/site-packages/../../libpython3.5m.so.1.0 (0x00007f3f972ff000)
libc.so.6 => /lib64/libc.so.6 (0x00007f3f96f6b000)
libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f3f96c64000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f3f96a4e000)
/lib64/ld-linux-x86-64.so.2 (0x000055a204b8f000)
libutil.so.1 => /lib64/libutil.so.1 (0x00007f3f9684b000
```

**Comment by ostrokach** [comment]
I get this error message when I try to compile `mysqlclient` using the conda-forge docker container: condaforge/linux-anvil:latest.

Conda recipe is as follows:

```
package:
  name: mysqlclient
  version: "1.3.8.dev"

source:
  git_url: https://github.com/PyMySQL/mysqlclient-python.git

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - python
    - mysql-connector-c
  run:
    - python
    - mysql-connector-c

test:
  imports:
    - MySQLdb

about:
  home: https://github.com/PyMySQL/mysqlclient-python
  license: GNU General Public License (GPL)
  summary: 'Python interface to MySQL'
```
